#!/usr/bin/env perl
#
# a Daemon::Control script for controlling the nginx frontend backend server
# for the MiDaS website. This script can start and stop the server process, as
# per a standard init script. It can also generate an LSB-compliant init script
# using
#
#   nginx get_init_file > /etc/init.d/nginx
#
# jt6 20141212 WTSI

use strict;
use warnings;

use Cwd;
use Daemon::Control;

my $name        = 'MiDaS nginx server';
my $sdesc       = 'Start MiDaS nginx server';
my $desc        = 'Start nginx server as a frontend for the MiDaS webapp';

my $app_home    = getcwd;
my $program     = 'nginx';
my $config      = $app_home . '/test_server/nginx.conf';

my $pid_file    = $app_home . '/test_server/nginx.pid';

Daemon::Control->new( {
    name        => $name,
    lsb_start   => '$remote_fs $syslog',
    lsb_stop    => '$remote_fs $syslog',
    lsb_sdesc   => $sdesc,
    lsb_desc    => $desc,

    # user        => 'www-data',
    # group       => 'www-data',
    directory   => $app_home,
    program     => "$program -c $config",

    pid_file    => $pid_file,
    stderr_file => $app_home . '/nginx.out',
    stdout_file => $app_home . '/nginx.out',

    fork        => 2,
} )->run;
