#!/usr/bin/env perl
#
# a Daemon::Control script for controlling the starman backend server for the
# MIDAS website. This script can start and stop the server process, as per a
# standard init script. It can also generate an LSB-compliant init script using
#
#   starman get_init_file > /etc/init.d/starman
#
# jt6 20141212 WTSI

use strict;
use warnings;

use Cwd;
use Daemon::Control;

my $name        = 'MIDAS starman server';
my $sdesc       = 'Start MIDAS starman server',
my $desc        = 'Start starman server to run the MIDAS webapp backend',

my $app_home    = '/www/jt6/MIDAS';

my $program     = 'starman';
my $port        = ':8000';
my $environment = 'development';
my $workers     = 5;
my $app         = 'dist/bin/app.pl';

my $pid_file    = '/var/run/starman.pid';
my $access_log  = '/var/log/starman/access.log';
my $error_log   = '/var/log/starman/error.log';

Daemon::Control->new( {
    name        => $name,
    lsb_start   => '$nginx',
    lsb_stop    => '$nginx',
    lsb_sdesc   => $sdesc,
    lsb_desc    => $desc,

    # user        => 'www-data',
    # group       => 'www-data',
    directory   => $app_home,
    program     => "$program --listen $port -E $environment --workers $workers $app",

    pid_file    => $pid_file,
    stderr_file => $access_log,
    stdout_file => $error_log,

    fork        => 2,
} )->run;
